### ISSUE TITLE
Invisible fields get wiped out

### ISSUE THREAD

**Issue by bardo** [ptomaszek/dummy-form-filler#11]
I have a form which spans multiple tabs, coded in bootstrap. When filling the form, invisible fields are not filled. This is not ideal for my use case, but I understand the reasoning behind it and it's fine.

Problem is, when switching tabs and filling again, the previously filled fields get wiped out. This means that only one tab can be auto-filled and the rest has to be done by hand.

The solution I propose is to keep filling only the visible fields, but not emptying the invisible ones.

Bootstrap reference for tab coding/behavior: http://getbootstrap.com/javascript/#tabs

**Comment by ptomaszek** [comment]
Can't do exaclty what you've proposed because reseting a form works in a scope of the entire ```<form>``` element, not it's particular fields (it's about HTML DOM mechanism for the Form object).

A workaround would be to disable repopulating. Therefore you could use the plugin on each tab knowing the data on others won't be cleared.

Please use this custom version with repopulating-off: https://github.com/ptomaszek/dummy-form-filler/blob/repopulate-off/bin/dummy-form-filler.xpi
Another one that should be filling up invisible fields (but I haven't tested it with bootstrap tabs): https://github.com/ptomaszek/dummy-form-filler/blob/populate-invisible/bin/dummy-form-filler.xpi

Choose whichever suits you better.

*I haven't mastered making the plugin configurable yet but I see there are more and more reasons to get into this...*
